# Generated by Django 2.2.1 on 2019-05-19 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190519_1402'),
    ]

    operations = [
        migrations.DeleteModel(
            name='man',
        ),
    ]
