# Generated by Django 2.2.1 on 2019-05-19 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_man'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Man',
        ),
    ]
