# Generated by Django 2.2.1 on 2019-05-24 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_man'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('My_Perm', 'My Perm'),)},
        ),
    ]
